### ISSUE TITLE
Can't serve the project

### ISSUE THREAD

**Issue by nechita** [taylorbryant/tailwind-jekyll#1]
Hey Taylor, I started using your starter kit for a new project I'm doing, but the project failed to start.

I've done some changes to run the kit:
Changed
```javascript
const jekyll = child.spawn('jekyll', ['serve',
    '--watch',
    '--incremental',
    '--drafts'
  ]);
```

with
```javascript
const jekyll = child.exec('jekyll serve --watch --incremental --drafts');
```

I'm not familiar with Gulp, so this might not be the Gulp way of doing things.

**Comment by hv-taylor** [comment]
Hey, thanks for letting me know about this! What OS are you using?

**Comment by taylorbryant** [comment]
Hey, thanks for letting me know about this! What OS are you using?

**Comment by nechita** [comment]
Hey @taylorbryant 
Windows 10, x64
node 8.1.2
npm 5.3.0

**Comment by taylorbryant** [comment]
It looks like running spawn on the child process doesn't play nice with Windows. I'm going to work on a platform-agnostic way of doing this.

FYI: I fixed an issue I found with changes to src/style.css not triggering a rebuild. I'm not sure if you ran into that issue yet, but it should be fixed now.

I'm also considering adding UnCSS to this starter project, but I'm a little apprehensive, because it requires more setup on the user's part. Is that something you'd benefit from?

**Comment by nechita** [comment]
Hey @taylorbryant UnCSS can be useful, but I think the benefit of it would be marginal. From what I've read, in v 0.2.0 we will have more advanced configuration options, so you would be able to avoid importing utilities you aren't using: https://github.com/tailwindcss/tailwindcss/issues/107

Imho this starter kit should be easy to use by any developer with limited experience.

But it's your project, your vision :P, so you get to decide how it should evolve.

**Comment by psren** [comment]
> in v 0.2.0 we will have more advanced configuration options, so you would be able to avoid importing utilities you aren't using

This is still open in the roadmap and not done for v0.2.0 (as far as I see) ;-)

**Comment by taylorbryant** [comment]
@nechita I completely agree. I'll probably just add some instructions to the readme file for setting up UnCSS.

9852edc33012d1388075f67701fda7664f7472e5 should fix your issue with serving Jekyll. I'll test and verify once I get my hands on a Windows machine tomorrow.

**Comment by taylorbryant** [comment]
8cfb404f93838dc5e8277f5fdb57e3797cb63a5a fixes this issue. Let me know if you run into any other issues.
