### ISSUE TITLE
Confused about implementation

### ISSUE THREAD

**Issue by svmadiraju** [taylorbryant/tailwind-jekyll#18]
Hi there,
Thanks for posting this starter kit. I've been successfully running it locally and have been able to use Tailwind perfectly well.

I have completed my site and now wish to publish it to GitHub Pages - however, I hit a roadblock and am not sure how to proceed with this. After pushing all the site files to a repo, I activate GitHub Pages for the repo and see the website load up; however, none of the CSS is rendered, neither the `style.css` file in your template that injects Tailwind, nor my own custom css file. 

I know this is not an issue but I did not know where else to ask. Do you have any advice as to how this can be resolved? I would greatly appreciate any guidance!

**Comment by taylorbryant** [comment]
Hey, @svmadiraju! I'm glad you like the starter.

Unfortunately, you won't be able to host your site on GitHub pages like you would a traditional Jekyll site. The starter uses Gulp (to build Tailwind, run Purgecss, etc.), and, as a result, requires a build step.

I recommend deploying your GitHub repo to [Netlify](https://netlify.com). Netlify is incredible. Once you've linked your GitHub repo, Netlify builds your site and generates a preview link for each commit.

Here's a step-by-step guide: https://www.netlify.com/blog/2016/09/29/a-step-by-step-guide-deploying-on-netlify/.

Thanks for reaching out! If you have any other questions or need help, I'm happy to help.
