### ISSUE TITLE
Watcher not picking up changes in _posts

### ISSUE THREAD

**Issue by netm** [taylorbryant/tailwind-jekyll#19]
Hi there - thanks so much for this project, it's been a great way for me to transition into using Tailwind.

I have a problem where the 'npm run start' command watches things well in regards to css and template changes but it doesn't pick up changes to, or additions to, files in /_posts/ I see you have your own repo with a blog made using this code - did you have the same problems?

Many thanks from NZ.

**Comment by taylorbryant** [comment]
Hey! I have no idea what happened, but GitHub didn't notify me about this issue. Are you using `.markdown` as the extension for your posts by any chance?

**Comment by netm** [comment]
Hi there - thanks for getting back to me, I was using .md :-)  I actually switched to your Gatsby goodness  and loving it! So dumped the Jekyll one and can't offer anymore insight.
