### ISSUE TITLE
Update Tailwind to v0.7.4

### ISSUE THREAD

**Issue by Courtny** [taylorbryant/tailwind-jekyll#20]
Greetings! I was poking around and looking to use this for a small project test ~ perhaps updating to the latest release would be good?

I tried to submit a pull request but receiving authentication errors.

https://github.com/tailwindcss/tailwindcss/releases/tag/v0.7.4

**Comment by taylorbryant** [comment]
I somehow didn't get a notification about this. I'll get this taken care of. Thank you for letting me know!
